// One-time migration helper: dumps the real, already-accumulated local
// thinking-spaces.sqlite database into a SQL script of INSERT
// statements that can be applied once to the D1 database backing the
// deployed Worker (see CLAUDE.md's Hosting section and worker/DEPLOY.md)
// -- this is what actually gets the person's real Spaces/blocks/Trail
// history into the hosted version, rather than starting the hosted app
// from an empty database.
//
// Run this from inside backend/ (so it can find its own node_modules
// and data/ folder, same as the app itself):
//   node export-to-d1.mjs
// Then copy the resulting data-export.sql into worker/ and apply it:
//   npx wrangler d1 execute thinking-spaces --remote --file=data-export.sql
//
// Only ever needs running once. Templates use INSERT OR IGNORE (in case
// worker/templates-seed.sql already seeded the 6 built-in ones first --
// see gardners-hub's own DEPLOY.md for the same reasoning); every other
// table uses a plain INSERT, since those rows are the person's real,
// never-duplicated data and a genuine primary-key collision there would
// mean something worth stopping and looking at, not silently ignoring.

import Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DB_PATH = process.env.THINKING_SPACES_DB_PATH || path.join(__dirname, 'data', 'thinking-spaces.sqlite');
const OUTPUT_PATH = path.join(__dirname, 'data-export.sql');

const db = new Database(DB_PATH, { readonly: true });

function sqlValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function dumpTable(table, columns, { orIgnore = false } = {}) {
  const rows = db.prepare(`SELECT ${columns.join(', ')} FROM ${table}`).all();
  const verb = orIgnore ? 'INSERT OR IGNORE' : 'INSERT';
  const statements = rows.map((row) => {
    const values = columns.map((col) => sqlValue(row[col]));
    return `${verb} INTO ${table} (${columns.join(', ')}) VALUES (${values.join(', ')});`;
  });
  return { statements, count: rows.length };
}

// Dependency order matters even though D1 may not strictly enforce the
// foreign keys on bulk insert: templates before spaces (template_id),
// spaces before blocks/workspaces/trail_entries (space_id).
const tables = [
  ['templates', ['id', 'name', 'block_arrangement', 'created_at', 'updated_at'], { orIgnore: true }],
  ['spaces', ['id', 'title', 'template_id', 'status', 'tags', 'goal', 'categories', 'accent', 'origin', 'due_date', 'created_at', 'updated_at']],
  ['blocks', ['id', 'space_id', 'type', 'content', 'properties', 'position', 'created_at', 'updated_at']],
  ['workspaces', ['id', 'space_id', 'name', 'created_at', 'updated_at']],
  ['trail_entries', ['id', 'space_id', 'kind', 'summary', 'note', 'skeleton_snapshot', 'created_at']],
  ['activity_log', ['id', 'space_id', 'space_title', 'kind', 'summary', 'created_at']],
];

const lines = [
  '-- Data export from the real local thinking-spaces.sqlite database.',
  '-- Generated by backend/export-to-d1.mjs -- apply once to a fresh D1',
  '-- database (after schema.sql and templates-seed.sql) with:',
  '--   npx wrangler d1 execute thinking-spaces --remote --file=data-export.sql',
  '-- run from worker/, after copying this file there.',
  '',
];
const counts = [];
for (const [table, columns, options] of tables) {
  const { statements, count } = dumpTable(table, columns, options);
  counts.push(`${count} ${table}`);
  lines.push(`-- ${table} (${count} row${count === 1 ? '' : 's'})`, ...statements, '');
}

fs.writeFileSync(OUTPUT_PATH, lines.join('\n'));
console.log(`Wrote ${OUTPUT_PATH}:`);
counts.forEach((line) => console.log(`  ${line}`));
