-- Built-in Resource Templates seed data (D1). Generated from backend/src/db/seedResourceTemplates.js --
-- do not hand-edit; regenerate from that file if a Resource Template changes.
-- Apply with: wrangler d1 execute thinking-spaces --remote --file=resource-templates-seed.sql

INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-aphorism', 'aphorism', 'Aphorism', '[{"name":"The Saying","prompt":"What is the exact wording?"},{"name":"What It Means","prompt":"What is your own gloss on it?"},{"name":"When It Applies","prompt":"When have you actually reached for this?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-art-piece', 'art piece', 'Art Piece', '[{"name":"What It Depicts","prompt":"What is the subject or form of the piece?"},{"name":"Technique or Choices","prompt":"What formal choices stand out -- medium, composition, technique?"},{"name":"What It Evokes","prompt":"What does it actually make you feel or notice?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-article', 'article', 'Article', '[{"name":"Thesis","prompt":"What is the article''s central claim?"},{"name":"Evidence Used","prompt":"What does it lean on to support that claim?"},{"name":"Your Take","prompt":"Where do you agree or disagree, and why?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-book', 'book', 'Book', '[{"name":"Core Argument or Story","prompt":"What is this book actually arguing, or what does it depict?"},{"name":"Key Passages","prompt":"Which specific passages, scenes, or quotes are worth remembering?"},{"name":"Personal Notes","prompt":"What are your own reactions or takeaways so far?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-debate', 'debate', 'Debate', '[{"name":"Position For","prompt":"What is the strongest case for this position?"},{"name":"Position Against","prompt":"What is the strongest case against it?"},{"name":"Where You Land","prompt":"Where do you actually come down, and why?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-essay', 'essay', 'Essay', '[{"name":"Central Claim","prompt":"What is the essay''s central claim?"},{"name":"Supporting Moves","prompt":"How does the argument actually build?"},{"name":"Where It’s Weakest","prompt":"Where does the argument feel least convincing?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-film', 'film', 'Film', '[{"name":"Plot / Premise","prompt":"What is the film actually about, on its surface?"},{"name":"Notable Scenes","prompt":"Which specific scenes are worth remembering?"},{"name":"What It’s Really About","prompt":"What theme sits underneath the plot?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-lecture', 'lecture', 'Lecture', '[{"name":"Main Claims","prompt":"What was actually argued or taught?"},{"name":"Notable Moments","prompt":"Was there a specific example, aside, or turn of phrase worth keeping?"},{"name":"Open Questions","prompt":"What did it leave unresolved for you?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-lesson', 'lesson', 'Lesson', '[{"name":"What It Teaches","prompt":"What is the actual skill or knowledge being taught?"},{"name":"How It’s Structured","prompt":"What is the teaching approach -- steps, examples, drills?"},{"name":"Where You’re Stuck","prompt":"What still feels unclear or unpracticed?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-parable', 'parable', 'Parable', '[{"name":"The Story","prompt":"What literally happens in the parable?"},{"name":"The Lesson","prompt":"What is it meant to teach?"},{"name":"Where It Applies","prompt":"What real situation does it actually illuminate?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-poem', 'poem', 'Poem', '[{"name":"The Text or Its Gist","prompt":"What does the poem actually say, or what is it about?"},{"name":"Imagery & Form","prompt":"What stands out about its imagery, structure, or sound?"},{"name":"What It Resonates With","prompt":"What in your own life does this connect to?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-riddle', 'riddle', 'Riddle', '[{"name":"The Riddle Itself","prompt":"What is the exact wording?"},{"name":"The Answer (if known)","prompt":"What is the answer, if you know it?"},{"name":"Why It Works","prompt":"What is the trick or logic behind it?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-seminar', 'seminar', 'Seminar', '[{"name":"Format & Participants","prompt":"Who was involved, and how was it run?"},{"name":"Main Threads","prompt":"What were the actual threads of discussion?"},{"name":"Takeaways","prompt":"What are you leaving with?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-song', 'song/musical piece', 'Song/Musical Piece', '[{"name":"Lyrics or Theme","prompt":"What is it actually about or saying?"},{"name":"Musical Character","prompt":"What stands out about its mood, structure, or instrumentation?"},{"name":"Personal Association","prompt":"Why does this particular piece matter to you?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-story', 'story', 'Story', '[{"name":"What Happens","prompt":"What actually happens in the story?"},{"name":"Characters & Stakes","prompt":"Who is involved, and what do they stand to lose or gain?"},{"name":"What It’s Really About","prompt":"What theme sits underneath the plot?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-video', 'video', 'Video', '[{"name":"What It Covers","prompt":"What is the video actually about?"},{"name":"Key Moments","prompt":"Which specific moments or timestamps are worth returning to?"},{"name":"Your Reaction","prompt":"What was your own response to it?"}]');
INSERT OR IGNORE INTO resource_templates (id, type, label, facets) VALUES ('resource-template-website', 'website', 'Website', '[{"name":"What It’s For","prompt":"What is this site actually for?"},{"name":"How You Use It","prompt":"How do you actually engage with it?"},{"name":"Reliability / Trust","prompt":"How much do you trust what’s there, and why?"}]');
