-- Built-in Templates seed data (D1). Generated from backend/src/db/seedTemplates.js --
-- do not hand-edit; regenerate from that file if a Template changes.
-- Apply with: wrangler d1 execute thinking-spaces --remote --file=templates-seed.sql

INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-inquiry-analytical', 'Inquiry / Analytical', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"list","content":{"items":[],"laneLabel":"Premises"},"properties":{"skeletonLane":"premises"},"position":1},{"type":"list","content":{"items":[],"laneLabel":"Evidence"},"properties":{"skeletonLane":"evidence"},"position":2},{"type":"list","content":{"items":[],"laneLabel":"Open Questions"},"properties":{"skeletonLane":"open-questions"},"position":3},{"type":"list","content":{"items":[],"laneLabel":"Tensions"},"properties":{"skeletonLane":"tensions"},"position":4},{"type":"text","content":{"tag":null,"text":""},"properties":{"skeletonRole":"current-best-articulation"},"position":5},{"type":"text","content":{"tag":null,"text":"Steelman: before finalizing, what is the strongest case against your current conclusion?"},"properties":{},"position":6}]');
INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-person-reflection', 'Person-Reflection', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"list","content":{"items":[],"laneLabel":"What I Understand"},"properties":{"skeletonLane":"premises"},"position":1},{"type":"list","content":{"items":[],"laneLabel":"Evidence"},"properties":{"skeletonLane":"evidence"},"position":2},{"type":"list","content":{"items":[],"laneLabel":"Open Qs"},"properties":{"skeletonLane":"open-questions"},"position":3},{"type":"list","content":{"items":[],"laneLabel":"Growth Edges"},"properties":{"skeletonLane":"tensions"},"position":4},{"type":"text","content":{"tag":null,"text":""},"properties":{"skeletonRole":"current-best-articulation"},"position":5},{"type":"text","content":{"tag":null,"text":"Steelman: before finalizing, what is the strongest case against your current conclusion?"},"properties":{},"position":6}]');
INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-technical-practical', 'Technical / Practical', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"list","content":{"laneLabel":"Progress Log","items":[{"id":"seed-log-1","text":"Started this","date":"2026-09-01"}]},"properties":{},"position":1},{"type":"list","content":{"laneLabel":"Milestones","items":[{"id":"seed-milestone-1","text":"Define the goal","checkbox":false}]},"properties":{},"position":2}]');
INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-life-management', 'Life Management', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"list","content":{"laneLabel":"Timeline","items":[{"id":"seed-timeline-1","text":"Started thinking about this","date":"2026-09-01"}]},"properties":{},"position":1},{"type":"list","content":{"laneLabel":"Goals","items":[{"id":"seed-goal-1","text":"Decide by...","checkbox":false}]},"properties":{},"position":2},{"type":"list","content":{"laneLabel":"Ledger","items":[{"id":"seed-ledger-1","text":"Starting point","number":0}]},"properties":{},"position":3}]');
INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-creative', 'Creative', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"media","content":{"mediaType":"image","url":"data:image/svg+xml,%3Csvg%20xmlns%3D''http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg''%20width%3D''320''%20height%3D''180''%3E%3Crect%20width%3D''100%25''%20height%3D''100%25''%20fill%3D''%23ddd''%2F%3E%3Ctext%20x%3D''50%25''%20y%3D''50%25''%20dominant-baseline%3D''middle''%20text-anchor%3D''middle''%20font-family%3D''sans-serif''%20font-size%3D''16''%3EMood%2Freference%20image%3C%2Ftext%3E%3C%2Fsvg%3E","caption":""},"properties":{},"position":1},{"type":"list","content":{"laneLabel":"Influences / Notes","items":[{"id":"seed-influence-1","text":"First influence or reference to track"}]},"properties":{},"position":2}]');
INSERT OR IGNORE INTO templates (id, name, block_arrangement) VALUES ('template-problem-formulation', 'Problem Formulation', '[{"type":"text","content":{"tag":null,"text":""},"properties":{},"position":0},{"type":"list","content":{"laneLabel":"Lenses to Consider","items":[{"id":"seed-lens-1","text":"Phenomenology","checkbox":false},{"id":"seed-lens-2","text":"Philosophy","checkbox":false},{"id":"seed-lens-3","text":"History","checkbox":false},{"id":"seed-lens-4","text":"Etymology","checkbox":false},{"id":"seed-lens-5","text":"Anthropology","checkbox":false},{"id":"seed-lens-6","text":"Epistemology","checkbox":false}]},"properties":{},"position":1},{"type":"formulation","content":{"statement":"","support":[],"confidence":"tentative"},"properties":{},"position":2}]');

